---
name: API-Build
run-name: API Build Pipeline
on:
  workflow_dispatch:
    inputs:
      force_pkg:
        description: 'Build package (or XOR)'
        type: string
        default: ''
        required: true
      build_pkg_group:
        description: 'Build package group'
        type: string
        default: ''
        required: false
      commit_sha:
        description: 'Commit SHA for selection'
        type: string
        default: ''
        required: false
      vyos-build-commit:
        description: 'vyos-build commit id (opt.)'
        type: string
        default: ''
        required: false
      upload_debs:
        description: 'Upload debs & build repo'
        type: boolean
        default: true
        required: false
      build_iso:
        description: 'Build .iso'
        type: boolean
        default: false
        required: false
      upload_iso:
        description: 'Upload .iso'
        type: boolean
        default: true
        required: false
  workflow_call:
    inputs:
      force_pkg:
        description: 'Build package (or XOR)'
        type: string
        default: 'None'
        required: false
      build_pkg_group:
        description: 'Build package group'
        type: string
        default: 'None'
        required: false
      commit_sha:
        description: 'Commit SHA for selection'
        type: string
        default: ''
        required: false
      vyos-build-commit:
        description: 'vyos-build commit id (opt.)'
        type: string
        default: ''
        required: false
      upload_debs:
        description: 'Upload debs & build repo'
        type: boolean
        default: true
        required: false
      build_iso:
        description: 'Build .iso'
        type: boolean
        default: false
        required: false
      upload_iso:
        description: 'Upload .iso'
        type: boolean
        default: true
        required: false

jobs:
  pipeline:
    uses: ./.github/workflows/build_initial.yml
    secrets: inherit
    with:
      force_pkg: ${{ inputs.force_pkg }}
      build_pkg_group: ${{ inputs.build_pkg_group }}
      commit_sha: ${{ inputs.commit_sha }}
      vyos-build-commit: ${{ inputs.vyos-build-commit }}
      upload_debs: ${{ inputs.upload_debs }}
      build_iso: ${{ inputs.build_iso }}
      upload_iso: ${{ inputs.upload_iso }}
