name: Build .iso
run-name: "[${{ github.ref_name }}] Build .iso"
on:
  workflow_call:
    inputs:
      upload_iso:
        required: true
        type: boolean
      upstream_repo_commit:
        required: true
        type: string
      smoketest:
        required: true
        type: boolean
      version:
        required: false
        type: string
    secrets:
      REPOHOST:
        required: true
      GPGKEY:
        required: false
      MINISIGN_KEY:
        required: true
      UPLOADREPO:
        required: true
      RELEASE_PAT:
        required: true
    outputs:
      VERSION: 
        value: ${{ jobs.buildiso.outputs.VERSION }}
      REPOHASH:
        value: ${{ jobs.buildiso.outputs.REPOHASH }}

  workflow_dispatch:
   inputs:
      upload_iso:
        description: 'Upload .iso'
        default: true
        type: boolean
      upstream_repo_commit:
        description: 'Upstream repo SHA (opt.)'
        default: ''
        type: string
      # We don't allow manual build of smoketest .iso here
      version:
        description: 'Version (opt.)'
        default: ''
        type: string

defaults:
  run:
    shell: bash

env:
  BUILD_BRANCH: ${{ github.ref_name }}
  BUILD_ARCH: amd64

jobs:
  buildiso:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.buildiso.outputs.VERSION }}
      REPOHASH: ${{ steps.buildiso.outputs.REPOHASH }}
    container:
      image: ${{ vars.UPSTREAM_MAIN_ROUTER_REPO }}:${{ github.ref_name }}
      options: --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0
      volumes:
        - /dev:/dev
    steps:
      - name: Print inputs
        run: |
          echo "upstream_repo_commit: ${{ inputs.upstream_repo_commit }}"
          echo "upload_iso: ${{ inputs.upload_iso }}"
          echo "smoketest: ${{ inputs.smoketest }}"
          echo "version: ${{ inputs.version }}"

      - name: Set safe-dir
        run: git config --global --add safe.directory '*'

      - name: Checkout upstream repo
        uses: actions/checkout@v4
        with:
          repository: '${{ vars.UPSTREAM_MAIN_ROUTER_REPO }}'
          ref: ${{ github.ref_name }}
          show-progress: true
          fetch-depth: 0

      - name: Reset repo
        run: git reset --hard ${{ inputs.upstream_repo_commit }}

      - name: Checkout my repository
        id: myRepoCheckout
        run: git clone --quiet https://${{ secrets.ROUTER_SOURCE_REPO_TOKEN }}@${{ secrets.ROUTER_SOURCE_REPO }} --single-branch -b ${{ env.BUILD_BRANCH }} _moveme &>/dev/null

      - name: Move files
        run: |
          mv -f _moveme/.scripts ./
          mv -f _moveme/debrand.sh ./
          rm -rf _moveme

      - name: Get GPG key
        run: |
          [ -n "${{ secrets.GPGKEY }}" ] && echo "${{ secrets.GPGKEY }}" > $(pwd)/gpgpubkey \
          || curl -sLo $(pwd)/gpgpubkey http://${{ secrets.REPOHOST }}/${{ env.BUILD_BRANCH }}/pgp-key.public
          [ -e $(pwd)/gpgpubkey ] || { echo "You must provide your PGP key" && exit 1 ; }

      - name: Add minisign pubkey
        run: |
          curl -sLo data/live-build-config/includes.chroot/usr/share/vyos/keys/vyos-release.minisign.pub http://${{ secrets.REPOHOST }}/noos-primary.minisign.pub
          curl -sLo data/live-build-config/includes.chroot/usr/share/vyos/keys/vyos-backup.minisign.pub  http://${{ secrets.REPOHOST }}/noos-secondary.minisign.pub
          curl -sLo data/live-build-config/includes.chroot/usr/share/vyos/keys/vyos-release.pub.asc http://${{ secrets.REPOHOST }}/${{ env.BUILD_BRANCH }}/pgp-key.public

      # https://www.freexian.com/lts/extended/docs/how-to-use-extended-lts/
      # Fix for ${{ vars.UPSTREAM_MAIN_ROUTER_REPO }}@ee9b739
      # https://github.com/${{ vars.UPSTREAM_MAIN_ROUTER_REPO }}/commit/ee9b7396b2d83d19a782186369427aded05c2b82
      - name: "Patch: Include upstream Freexian"
        run: |
          sudo wget -q https://deb.freexian.com/extended-lts/archive-key.gpg -O elts-archive-key.gpg \
            && sudo mv elts-archive-key.gpg /etc/apt/trusted.gpg.d/freexian-archive-extended-lts.gpg
          echo "deb http://${{ secrets.FREEXIAN_REPO_HOST }} buster main contrib non-free" > /etc/apt/sources.list.d/extended-lts.list
          sed -i 's|local.deb.vyos.io/extended-lts/|${{ secrets.FREEXIAN_REPO_HOST }}|' data/defaults.json

      - name: Debrand
        run: ./debrand.sh -b ${{ env.BUILD_BRANCH }}

      - name: Build ISO
        id: buildiso
        run: |
          VERSIONBASE="$(git describe --tags --abbrev=0)"
          BUILDTIME="$(date -u +%Y%m%d%H%M)"
          ROLLSTAB='stable'
          [ -z "${{ inputs.version }}" ] \
            && VERSION="${VERSIONBASE}-${ROLLSTAB}-${BUILDTIME}" \
            || VERSION='${{ inputs.version }}'
          PKGLIST="${VERSION}.pkglst.txt"

          REPOHASH="$(curl -s 'http://${{ secrets.REPOHOST }}/${{ env.BUILD_BRANCH }}/dists/${{ env.BUILD_BRANCH }}/Release' | grep 'main/binary-${{ env.BUILD_ARCH }}/Packages$' | tail -1 | awk '{print $1}')"

          echo "VERSIONBASE=${VERSIONBASE}" | tee -a $GITHUB_OUTPUT
          echo "BUILDTIME=${BUILDTIME}"     | tee -a $GITHUB_OUTPUT
          echo "ROLLSTAB=${ROLLSTAB}"       | tee -a $GITHUB_OUTPUT
          echo "VERSION=${VERSION}"         | tee -a $GITHUB_OUTPUT
          echo "PKGLIST=${PKGLIST}"         | tee -a $GITHUB_OUTPUT
          echo "REPOHASH=${REPOHASH}"       | tee -a $GITHUB_OUTPUT

          smoketest=${{ inputs.smoketest }}
          [ -z "${smoketest}" ] && smoketest=false

          apt-get update && apt-get install -y python3-git

          ./configure \
          --architecture ${{ env.BUILD_ARCH }} \
          --debug \
          --build-by Anonymous \
          --build-type release \
          --version "${VERSION}" \
          --vyos-mirror "http://${{ secrets.REPOHOST }}/${{ env.BUILD_BRANCH }}" \
          --custom-package="intel-microcode" \
          --custom-package="amd64-microcode" \
          --custom-package="apt-transport-https" \
          $(${smoketest} && echo "--custom-package vyos-1x-smoketest") \
          --custom-apt-key $(pwd)/gpgpubkey

          make iso

      - name: "Upload artifact: live-image"
        if: ${{ inputs.smoketest && steps.buildiso.outcome == 'success' }}
        uses: actions/upload-artifact@v4
        id: artifact-upload-smoketest
        with:
          name: ${{ steps.buildiso.outputs.VERSION }}-smoketest
          path: build/live-image-amd64.hybrid.iso
          retention-days: 1
          if-no-files-found: error

      - name: Collect package list
        if: ${{ steps.buildiso.outcome == 'success' }}
        id: collectpackagelist
        run: |
          echo "#######################################"
          echo "#  Generating installed package list  #"
          echo "#######################################"
          PKGLIST=${{ steps.buildiso.outputs.PKGLIST }}
          mkdir -p artifacts
          cp build/binary/live/filesystem.packages artifacts/${PKGLIST} \
          && buildCommit=$(jq -r '.build_git' build/chroot/usr/share/vyos/version.json) \
          && printf 'Built against ${{ vars.UPSTREAM_MAIN_ROUTER_REPO }}@%s\n' "${buildCommit}" | tee artifacts/${PKGLIST}.md \
          && printf '<details>\n<summary>Included packages</summary>\n\n|Package|Version|\n|---|---|\n' >> artifacts/${PKGLIST}.md \
          && cat build/binary/live/filesystem.packages | awk '{print "|"$1"|"$2"|"}' | tee -a artifacts/${PKGLIST}.md \
          && printf '\n</details>\n' >> artifacts/${PKGLIST}.md

      - name: Collect generated artifacts
        if: ${{ !inputs.smoketest && steps.collectpackagelist.outcome == 'success' }}
        id: collectimages
        run: |
          # Needs modification to support capturing additional images
          for fmt in iso ###qcow2 vdi vhdx
          do
            filename=vyos-${{ steps.buildiso.outputs.VERSION }}
            [ "${fmt}" = "iso" ] && filename="${filename}-${{ env.BUILD_ARCH }}"
            ls build/${filename}.${fmt} >/dev/null 2>&1 \
            && ln -s ../build/${filename}.${fmt} ./artifacts/${filename/vyos-/}.${fmt}
          done

          # VMware artifacts
          #ls build/vyos-${{ steps.buildiso.outputs.VERSION }}.ova >/dev/null        2>&1 && ln -s ../build/vyos-${{ steps.buildiso.outputs.VERSION }}.ova        ./artifacts/${{ steps.buildiso.outputs.VERSION }}.ova
          #ls build/vyos-${{ steps.buildiso.outputs.VERSION }}.ovf >/dev/null        2>&1 && ln -s ../build/vyos-${{ steps.buildiso.outputs.VERSION }}.ovf        ./artifacts/${{ steps.buildiso.outputs.VERSION }}.ovf
          #ls build/vyos-${{ steps.buildiso.outputs.VERSION }}.mf >/dev/null         2>&1 && ln -s ../build/vyos-${{ steps.buildiso.outputs.VERSION }}.mf         ./artifacts/${{ steps.buildiso.outputs.VERSION }}.mf
          #ls build/vyos-${{ steps.buildiso.outputs.VERSION }}-disk1.vmdk >/dev/null 2>&1 && ln -s ../build/vyos-${{ steps.buildiso.outputs.VERSION }}-disk1.vmdk ./artifacts/${{ steps.buildiso.outputs.VERSION }}-disk1.vmdk

          basename="${{ steps.buildiso.outputs.VERSION }}-${{ env.BUILD_ARCH }}"
          echo "BASENAME=${basename}" | tee -a $GITHUB_OUTPUT
          [ -e artifacts/${basename}.iso ]

      - name: minisign
        if: ${{ !inputs.smoketest && steps.collectimages.outcome == 'success' }}
        id: minisign
        working-directory: artifacts
        run: |
          [ -n "${{ secrets.MINISIGN_KEY }}" ] \
          && { \
            curl -sL $(curl -sL https://api.github.com/repos/jedisct1/minisign/releases/latest | jq -r '.assets[] | select(.name | match("linux.tar.gz$")) | .browser_download_url') | tar xvzf - --strip-components=2 minisign-linux/x86_64/minisign \
            && chmod +x minisign \
            && echo "${{ secrets.MINISIGN_KEY }}" > minisign.key \
            && echo ${{ secrets.MINISIGN_PASSWORD }} | ./minisign -s minisign.key -Sm ${{ steps.collectimages.outputs.BASENAME }}.iso
            rm -f minisign.key ; } \
          || { echo "minisign.key not provided. Not signing." ; }

      #- name: "Upload artifact: .iso"
      #  if: ${{ !inputs.smoketest && steps.minisign.outcome == 'success' }}
      #  uses: actions/upload-artifact@v4
      #  id: artifact-upload-release
      #  with:
      #    name: ${{ steps.buildiso.outputs.VERSION }}-release
      #    path: |
      #      artifacts/${{ steps.buildiso.outputs.PKGLIST }}
      #      artifacts/${{ steps.collectimages.outputs.BASENAME }}.iso
      #      artifacts/${{ steps.collectimages.outputs.BASENAME }}.iso.minisig
      #    retention-days: 1

      - name: Create release with artifact
        if: ${{ !inputs.smoketest && inputs.upload_iso && steps.collectimages.outcome == 'success' }}
        uses: softprops/action-gh-release@v2
        with:
          repository: ${{ secrets.UPLOADREPO }}
          token: ${{ secrets.RELEASE_PAT }}
          name: v${{ steps.buildiso.outputs.VERSION }}
          tag_name: 0-${{ steps.buildiso.outputs.BUILDTIME }}-${{ steps.buildiso.outputs.VERSIONBASE }}-${{ steps.buildiso.outputs.ROLLSTAB }}
          make_latest: true
          body_path: artifacts/${{ steps.buildiso.outputs.PKGLIST }}.md
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          files: |
            artifacts/${{ steps.buildiso.outputs.PKGLIST }}
            artifacts/${{ steps.collectimages.outputs.BASENAME }}.iso
            artifacts/${{ steps.collectimages.outputs.BASENAME }}.iso.minisig
