---
name: Build
run-name: Build Pipeline
on:
  workflow_dispatch:
    inputs:
      build_iso:
        description: 'Build .iso'
        default: false
        type: boolean
      upload_iso:
        description: 'Upload .iso'
        default: true
        type: boolean
      vyos-build-commit:
        description: 'vyos-build commit id (opt.)'
        required: false
        default: ''
        type: string
  workflow_call:
    inputs:
      build_iso:
        description: 'Build .iso'
        default: false
        type: boolean
      upload_iso:
        description: 'Upload .iso'
        default: true
        type: boolean
      vyos-build-commit:
        description: 'vyos-build commit id (opt.)'
        required: false
        default: ''
        type: string

env:
  BUILD_BRANCH: ${{ github.ref_name }}
  BUILD_FLAVOR: 1.5_Base
  BUILD_ARCH: amd64





jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      mymatrix: ${{ steps.getPackages.outputs.packages }}
      vyosbuildSHA: ${{ steps.getVyosBuildSHA.outputs.SHA }}
    steps:
      - name: Print workflow inputs
        run: |
          echo "build_iso: ${{ inputs.build_iso }}"
          echo "upload_iso: ${{ inputs.upload_iso }}"
          echo "vyos-build-commit: ${{ inputs.vyos-build-commit }}"

      - name: Set vyos-build commit id
        id: getVyosBuildSHA
        run: |
          [ -n "${{ inputs.vyos-build-commit }}" ] \
            && { echo "SHA=${{ inputs.vyos-build-commit }}" | tee -a $GITHUB_OUTPUT ; } \
            || { echo "SHA=$(curl -sL https://api.github.com/repos/vyos/vyos-build/commits/${{ env.BUILD_BRANCH }} | jq -r .'sha')" | tee -a $GITHUB_OUTPUT ; }

      - name: Print job outputs
        run: |
          echo "vyosbuildSHA: ${{ steps.getVyosBuildSHA.outputs.SHA }}"

  build-smoketest-iso:
    if: ${{ inputs.build_iso && inputs.upload_iso && !(cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) }}
    needs: [ setup ]
    uses: ./.github/workflows/build_iso.yml
    secrets: inherit
    with:
      vyosbuildSHA: ${{ needs.setup.outputs.vyosbuildSHA }}
      upload_iso: false
      smoketest: true

  smoketest:
    if: ${{ needs.build-smoketest-iso.result == 'success' && !(cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) }}
    needs: [ setup, build-smoketest-iso ]
    runs-on: ubuntu-24.04
    container:
      image: vyos/vyos-build:${{ github.ref_name }}
      options: --privileged --sysctl net.ipv6.conf.lo.disable_ipv6=0
      volumes:
        - /dev:/dev
    
    strategy:
      matrix:
        cmd: [
          'sudo make test',
          'sudo make testc',
          'sudo make testraid',
          'sudo make testtpm'
        ]
      fail-fast: false

    steps:
      - name: Set safe-dir
        run: git config --global --add safe.directory '*'

      - name: Checkout vyos-build
        uses: actions/checkout@v4
        id: vyosBuildCheckout
        with:
          repository: 'vyos/vyos-build'
          ref: ${{ github.ref_name }}
          show-progress: true
          fetch-depth: 0

      - name: Reset repo
        run: git reset --hard ${{ needs.setup.outputs.vyosbuildSHA }}

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-smoketest-iso.outputs.VYOSVER }}-smoketest
          path: build

      - name: Smoketest
        id: smoketest
        run: ${{ matrix.cmd }}

  build-release-iso:
    if: ${{ inputs.build_iso && !(cancelled() || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure')) }}
    needs: [ setup, smoketest ]
    uses: ./.github/workflows/build_iso.yml
    secrets: inherit
    with:
      vyosbuildSHA: ${{ needs.setup.outputs.vyosbuildSHA }}
      upload_iso: ${{ inputs.upload_iso }}
      smoketest: false
